### ISSUE TITLE
getting error!!

### ISSUE THREAD

**Issue by Shubham0209** [murugaratham/react-mirror#2]
hi, there
could you please let me knoe step by step instructions on how to run your code on my laptop.
i have downloaded node and when i try to run the code i get following errors.
![1](https://cloud.githubusercontent.com/assets/14998135/12985451/bcd8472a-d118-11e5-8fa8-1560e4f95018.jpg)
![2](https://cloud.githubusercontent.com/assets/14998135/12985452/bcde8324-d118-11e5-9ffc-5a808e404e54.jpg)
![3](https://cloud.githubusercontent.com/assets/14998135/12985453/bce322f8-d118-11e5-8ed7-256b5cfe5154.jpg)

**Comment by murugaratham** [comment]
hi @Shubham0209 sorry i didn't turn on notifications for issues, i've made a few changes and updated the readme.

Can you try cloning again then cd react-mirror & run npm install then npm run kiosk.

The server should be listening @ 8080 then open it in ur browser. I am exploring using [electron](https://github.com/atom/electron) to reduce the step of launching your browser manually and to wrap it as an application, pull requests welcome too though
