### ISSUE TITLE
Errors while running kiosk & start

### ISSUE THREAD

**Issue by Shreiya** [murugaratham/react-mirror#3]
Hi!

Could you help me out with what I can do to fix these errors? When I tested it on my Mac OSx, it ran smoothly with npm run kiosk, but when I tried the same on my pi terminal - it crashed.

#For npm install - 

![img_2628](https://cloud.githubusercontent.com/assets/18325987/21952767/1d935c4a-da4a-11e6-8df5-d4ecfa8fcf9a.JPG)

#For npm run kiosk - 

![img_2631](https://cloud.githubusercontent.com/assets/18325987/21952887/03886800-da4e-11e6-85d9-f5aee7e206fa.JPG)

![kiosk](https://cloud.githubusercontent.com/assets/18325987/21952889/1f844402-da4e-11e6-8205-d7bf3b9b7e47.jpg)

##For npm start - 

![img_2630](https://cloud.githubusercontent.com/assets/18325987/21952882/dd43edfe-da4d-11e6-8845-2feb8351264d.JPG)

**Comment by murugaratham** [comment]
Hi Shreiya,

Have you tried updating your node? You are on a very old version (0.10.29)

**Comment by Shreiya** [comment]
Thank you so much for that.

I think that was a major issue that got resolved. 
The next bug is in browserify and the certificates.

When I run kiosk, it starts looking at the bootstrap.js file and gives me the same error there.

For when I run start, I've attached the screenshots of what errors are displayed.

I managed to generate the certificates on the pi from the server. Could you explain in detail what I have to do now to get this to function?

(Again, thank you so much for helping me out. This react-mirror is a godsent)


![image](https://cloud.githubusercontent.com/assets/18325987/21953890/23f74bf4-da69-11e6-911a-d8a9bea6c45b.png)

![image](https://cloud.githubusercontent.com/assets/18325987/21953896/483d36e0-da69-11e6-8480-d5fc261df8aa.png)

![image](https://cloud.githubusercontent.com/assets/18325987/21953899/556b016c-da69-11e6-81bc-75756d88d0d5.png)

![image](https://cloud.githubusercontent.com/assets/18325987/21953902/5b68bcf8-da69-11e6-9dd3-ca94d41afd37.png)

**Comment by murugaratham** [comment]
Can you check under node_modules whether u have reactDOM? If it's not there you can do a manual install, npm do not resolve peer dependencies now

**Comment by Shreiya** [comment]
It seems that I do have it. I checked against your node modules and it all seems up to date. Is there anything else I could do?

**Comment by murugaratham** [comment]
You can see that it's unable to find reactDOM, react-css-transitition-replace need that, you can either try to remove that dependency or get reactDOM into the project, and also.. Can you copy paste the error message instead of screenshots, it's easier to look at

**Comment by Shreiya** [comment]
so according to the error, there is no reactDOM within the react-css-transition-replace node module's library. I'm going to try manually adding it there.

Here's the error message that comes when i run npm start. Sorry for not pasting it earlier.


pi@raspberrypi:~/Desktop/react-mirror $ npm start

> React-mirror@0.0.2-alpha start /home/pi/Desktop/react-mirror
> npm install && npm run build && node server.js -S -C localhost-cert.pem -K localhost-key.pem

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/nodemon/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/watchify/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

> React-mirror@0.0.2-alpha build /home/pi/Desktop/react-mirror
> npm run build-js && npm run build-css


> React-mirror@0.0.2-alpha build-js /home/pi/Desktop/react-mirror
> browserify src/main.js -o static/bundle.js

Error: Cannot find module 'react-dom/lib/ReactDOM' from '/home/pi/Desktop/react-mirror/node_modules/react-css-transition-replace/node_modules/react/lib'
    at /home/pi/Desktop/react-mirror/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/pi/Desktop/react-mirror/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/pi/Desktop/react-mirror/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/pi/Desktop/react-mirror/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/pi/Desktop/react-mirror/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/pi/Desktop/react-mirror/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:112:15)

npm ERR! Linux 4.4.21-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build-js"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! React-mirror@0.0.2-alpha build-js: `browserify src/main.js -o static/bundle.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the React-mirror@0.0.2-alpha build-js script 'browserify src/main.js -o static/bundle.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the React-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify src/main.js -o static/bundle.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs React-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls React-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/Desktop/react-mirror/npm-debug.log

npm ERR! Linux 4.4.21-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! React-mirror@0.0.2-alpha build: `npm run build-js && npm run build-css`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the React-mirror@0.0.2-alpha build script 'npm run build-js && npm run build-css'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the React-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-js && npm run build-css
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs React-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls React-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/Desktop/react-mirror/npm-debug.log

npm ERR! Linux 4.4.21-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! React-mirror@0.0.2-alpha start: `npm install && npm run build && node server.js -S -C localhost-cert.pem -K localhost-key.pem`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the React-mirror@0.0.2-alpha start script 'npm install && npm run build && node server.js -S -C localhost-cert.pem -K localhost-key.pem'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the React-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && npm run build && node server.js -S -C localhost-cert.pem -K localhost-key.pem
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs React-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls React-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/Desktop/react-mirror/npm-debug.log

**Comment by murugaratham** [comment]
No worries, can you navigate to '/home/pi/Desktop/react-mirror/node_modules/react-css-transition-replace/' 

And check if reactDOM is in there? If not try to do a manual npm -i ReactDOM at that dir 

If not, might want to take a look at react-css-transitition-replace project and see how they fix that issue. 

Would appreciate a PR :)

**Comment by Shreiya** [comment]
okay done that :) it took care of looking for react-dom

these are the new error messages - 

> React-mirror@0.0.2-alpha start /home/pi/Desktop/react-mirror
> npm install && npm run build && node server.js -S -C localhost-cert.pem -K localhost-key.pem

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/nodemon/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/watchify/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

> React-mirror@0.0.2-alpha build /home/pi/Desktop/react-mirror
> npm run build-js && npm run build-css


> React-mirror@0.0.2-alpha build-js /home/pi/Desktop/react-mirror
> browserify src/main.js -o static/bundle.js


> React-mirror@0.0.2-alpha build-css /home/pi/Desktop/react-mirror
> cat css/*.css > static/bundle.css

fs.js:558
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'localhost-cert.pem'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.<anonymous> (/home/pi/Desktop/react-mirror/server.js:26:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)

npm ERR! Linux 4.4.21-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! React-mirror@0.0.2-alpha start: `npm install && npm run build && node server.js -S -C localhost-cert.pem -K localhost-key.pem`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the React-mirror@0.0.2-alpha start script 'npm install && npm run build && node server.js -S -C localhost-cert.pem -K localhost-key.pem'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the React-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && npm run build && node server.js -S -C localhost-cert.pem -K localhost-key.pem
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs React-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls React-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/Desktop/react-mirror/npm-debug.log

PR coming right away!

**Comment by murugaratham** [comment]
Have you generate the cert? Look at readme.md. It can't find the cert, or u can npm run start-no-ssl, but without SSL, browser might keep promoting for permission, look at https://github.com/TalAter/annyang/blob/master/docs/FAQ.md

**Comment by murugaratham** [comment]
Gonna close this issue for inactivity
